### ISSUE TITLE
Install fails on Python 3.7

### ISSUE THREAD

**Issue by peterstangl** [DavidMStraub/rundec-python#1]
Error output of
```
pip install rundec
```
on a machine running Python 3.7:
```
Collecting rundec
  Using cached https://files.pythonhosted.org/packages/96/55/bcef2a930e13b0ba12f7bd6d9c41fc235ca27c1fa1a46982998c80ee78e0/rundec-0.0.1.tar.gz
Building wheels for collected packages: rundec
  Running setup.py bdist_wheel for rundec ... error
  Complete output from command /home/stangl/miniconda3/envs/python3_7_test/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-b8tsjfas/rundec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-lygmkyvj --python-tag cp37:
  running bdist_wheel
  running build
  running build_ext
  building '_rundec' extension
  creating build
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/CRunDec3
  gcc -pthread -B /home/stangl/miniconda3/envs/python3_7_test/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/stangl/miniconda3/envs/python3_7_test/include/python3.7m -c _rundec.cc -o build/temp.linux-x86_64-3.7/_rundec.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  _rundec.cc:3121:10: fatal error: CRunDec3/CRunDec.h: No such file or directory
   #include "CRunDec3/CRunDec.h"
            ^~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for rundec
  Running setup.py clean for rundec
Failed to build rundec
Installing collected packages: rundec
  Running setup.py install for rundec ... error
    Complete output from command /home/stangl/miniconda3/envs/python3_7_test/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-b8tsjfas/rundec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-3bu76cy1/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building '_rundec' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/CRunDec3
    gcc -pthread -B /home/stangl/miniconda3/envs/python3_7_test/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/stangl/miniconda3/envs/python3_7_test/include/python3.7m -c _rundec.cc -o build/temp.linux-x86_64-3.7/_rundec.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    _rundec.cc:3121:10: fatal error: CRunDec3/CRunDec.h: No such file or directory
     #include "CRunDec3/CRunDec.h"
              ^~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------

```

**Comment by DavidMStraub** [comment]
Thanks! This is because rundec binaries are built automatically on Travis on release and the last release was built before 3.7 appeared. I just pushed a patch version and hope it will build fine...

**Comment by peterstangl** [comment]
Another issue is that If I do
```
pip install rundec
```
I actually get
```
Downloading https://files.pythonhosted.org/packages/96/55/bcef2a930e13b0ba12f7bd6d9c41fc235ca27c1fa1a46982998c80ee78e0/rundec-0.0.1.tar.gz (68kB)
```
which means it loads **version 0.0.1**. This then does not compile.
Clearing the pip cache and using `pip install rundec --upgrade` does not change this...

**Comment by DavidMStraub** [comment]
This is because I released a new version that is not yet compiled ... hopefully fixed very soon. Sorry

**Comment by DavidMStraub** [comment]
The Linux binaries have been built successfully!
https://pypi.org/project/rundec/#files
This should work now.

Still waiting for MacOS and Windows.

**Comment by peterstangl** [comment]
I can confirm that the rundec installation now works on Python 3.7 (with rundec version 0.5.1).

**Comment by DavidMStraub** [comment]
Windows and MacOS packages are now there as well, and Python 3.7 added to Travis for the wcxf and wilson packages.

Thanks for pointing this out!

**Comment by rakircher** [comment]
I just tried to install 3.7.3 using download "Python-3.7.3.tar.xz" on my Linux Debian 9 machine and it failed miserably too.  The same Linux machine is successfully running Python 2.7.13 and 3.5.3.  I had to switch back to 2.7.13 because of some kind of encoding problem with pipes in version 3.5.3,  Please tell me if there is a stable version later than 3.5.3 that might work because I want to stick with Python 3 if possible.  
 
Terminal Log when running "sudo make install:
zipimport.ZipImportError: can't decompress data; zlib not available
Makefile:1130: recipe for target 'install' failed
make: *** [install] Error 1
dick@deb:~/PY/Python3.7.3/Python-3.7.3$ 
dick@deb:~/PY/Python3.7.3/Python-3.7.3$ 
dick@deb:~/PY/Python3.7.3/Python-3.7.3$ python3
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Current thread 0x00007f3f2c01c700 (most recent call first):
Aborted

Before that while running "make" and "make_test" I saw these problems:
dick@deb:~/PY/Python3.7.3/Python-3.7.3$ make test
 CC='gcc -pthread' LDSHARED='gcc -pthread -shared    ' OPT='-DNDEBUG -g -fwrapv -O3 -Wall' 	_TCLTK_INCLUDES='' _TCLTK_LIBS='' 	./python -E ./setup.py  build
running build
running build_ext
INFO: Can't locate Tcl/Tk libs and/or headers
INFO: Could not locate ffi libs and/or headers

Python build finished successfully!
The necessary bits to build these optional modules were not found:
_bz2                  _curses               _curses_panel      
_dbm                  _gdbm                 _hashlib           
_lzma                 _sqlite3              _ssl               
_tkinter              _uuid                 readline           
zlib                                                           
To find the necessary bits, look in setup.py in detect_modules() for the module's name.
The following modules found by detect_modules() in setup.py, have been
built by the Makefile instead, as configured by the Setup files:
_abc                  atexit                pwd      time                                                           
Failed to build these modules:
_ctypes                                                        
Could not build the ssl module!
Python requires an OpenSSL 1.0.2 or 1.1 compatible libssl with X509_VERIFY_PARAM_set1_host().
LibreSSL 2.6.4 and earlier do not provide the necessary APIs, https://github.com/libressl-portable/portable/issues/381

Unfortunately I have limited experience and knowledge outside of writing Python code, and usually rely on the Synaptic Package manager, but Debian lags behind the latest releases so I am stuck.
Thanks for any help.

**Comment by DavidMStraub** [comment]
So you are having problems installing Python itself? If so, then this is not the right place to ask (but I suggest you try [miniconda](https://docs.conda.io/en/latest/miniconda.html)) ...

**Comment by rakircher** [comment]
Thanks for the miniconda suggestion.  I downloaded
"Miniconda3-latest-Linux-x86_64.sh",  ran "bash
Miniconda3-latest-Linux-x86_64.sh ", and then set PYTHONPATH to
/home/dick/miniconda3, but ran into the same syntax errors in Python 3.7.3
than have been a problem with previous install attempts.  Here is the log
for it:

Do you wish the installer to initialize Miniconda3
by running conda init? [yes|no]
[no] >>> yes
Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site.py", line 73, in <module>
    import os
  File "/usr/local/lib/python3.7/os.py", line 25, in <module>
    import abc
ModuleNotFoundError: No module named 'abc'
If you'd prefer that conda's base environment not be activated on startup,
   set the auto_activate_base parameter to false:

conda config --set auto_activate_base false

Thank you for installing Miniconda3!

###### Of course it does not run either:

dick@deb:~/PY/Python3.7.3-Miniconda3$ python3
Failed to import the site module
  File "/usr/local/lib/python3.7/site.py", line 272
    return f'{userbase}/lib/python/site-packages' # SYNTAX ERROR
                                                ^
SyntaxError: invalid syntax
dick@deb:~/PY/Python3.7.3-Miniconda3$


I had Python 2.7 installed in my Debian 9 system, but now it no longer
works so I 'm really stuck!  ########

dick@deb:~/PY/Python3.7.3-Miniconda3$ python
  File "/usr/local/lib/python3.7/site.py", line 177
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
dick@deb:~/PY/Python3.7.3-Miniconda3$

######
It is probably inappropriate to bother you with questions, but if you can
just recommend what I should try next, it would greatly be appreciated.
I'm thinking Python 3.7.3 is not ready yet.  How would I install a late
mature Python 3.6.x? with miniconda3?

Thanks, Dick

PS-  conda list results:
dick@deb:~/miniconda3/bin$ conda list
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f62bee0c580 (most recent call first):
Aborted
dick@deb:~/miniconda3/bin$
dick@deb:~/miniconda3/bin$ cd ..
dick@deb:~/miniconda3$ conda list
bash: conda: command not found    ####### THIS SEEMS STRANGE, MAY BE A GOOD
CLUE.
dick@deb:~/miniconda3$ echo $PYTHONPATH
/home/dick/miniconda3
dick@deb:~/miniconda3$

**Comment by DavidMStraub** [comment]
No idea, something is wrong with paths. It's certainly not a Python 3.7 vs 3.6 problem.
